### ISSUE TITLE
How to get * or _ when the markdown is turned on?

### ISSUE THREAD

**Issue by nemonein** [extendify/block-options#319]
Hello.
I wish I could get `__init__`, but it's automatically translated to italics.
I've added \\, like \\_ but it does not work either.

Is there a way to get these letters?

**Comment by clubkert** [comment]
Hi @nemonein ,

Under the "More options" button at the top side of the editor click "EditorsKit Settings" and turn off the markdown formatting option. Thanks!

By the way, we've recently taken over the EditorsKit plugin. We'd love to hear more about how you use it and what suggestions you'd have. Feel free to let us know here or reach out directly to support@extendify.com.

Thanks!
Chris
