### ISSUE TITLE
Disable the Extendify button

### ISSUE THREAD

**Issue by rodrigo-arias** [extendify/block-options#320]
Hi, thanks for your work with this plugin. Is there any way to disable the Library button leading to Extendify added in 1.30?

![CleanShot 2021-06-18 at 16 34 58](https://user-images.githubusercontent.com/11416255/122608742-24036f80-d053-11eb-86f0-8c70abc43998.png)

The rest of EditorsKit blends well with Gutenberg, but this new button is not something I use and it gets a lot of attention. It can still be hidden with CSS but I didn't find an option for this alongside the rest of the settings.

Thanks

**Comment by clubkert** [comment]
Hi @rodrigo-arias - there will be an option to remove this in the next release, which we expect to be on Tuesday or Wednesday. We'll follow up when it is out. Thanks!

**Comment by rodrigo-arias** [comment]
Hi @clubkert do you have any updates regarding this? Thanks

**Comment by clubkert** [comment]
@rodrigo-arias thanks for the ping. I'm sorry I never circled back. There were a couple similar questions and I thought I followed up with them all, but missed yours.

We released a toggle to 'Disable Extendify" in the editor preference section (see the screenshot below). This will apply to the user that selects it.

![image](https://user-images.githubusercontent.com/2229643/125325626-62144c00-e2fe-11eb-951b-bfedfd2ac8b4.png)


We've gotten some reports of the "disable" button not working as it should in some environments and we'll have another update this week that should resolve that.

Alternatively, you can disable it for all users by adding the following as a mu-plugin:

`add_filter('extendifysdk_load_library', '__return_false');`

**Comment by rodrigo-arias** [comment]
Tested and works fine, always grateful to have global filters.
