### ISSUE TITLE
Unauthorized request for non-admin users

### ISSUE THREAD

**Issue by rodrigo-arias** [extendify/block-options#323]
Hi, I am getting an error for unauthorized request for non-admin users related to extendify-sdk.
That happens from v1.30, so maybe it's related to [this commit](https://github.com/extendify/block-options/commit/652a51c1622cb85da584f521f27c4d28ff6e8aba).

![CleanShot 2021-06-29 at 13 21 19](https://user-images.githubusercontent.com/11416255/123833747-0cdb4200-d8dd-11eb-8bbb-f0a22f2fdea8.png)

I would expect that if the user's role does not allow to access certain functionality, let's say the Library, it just hides the button instead of triggering an error.
Thanks you

**Comment by clubkert** [comment]
Thanks for reporting this @rodrigo-arias . We have solved this and it will go out with the next EditorsKit release.
