### ISSUE TITLE
EditorsKit interfere with SEO tags

### ISSUE THREAD

**Issue by corbrink** [extendify/block-options#325]
The plugin makes the product %title% “undefined” and does not display the product title.

Screenshot download [here](https://onlineart.gallery//wp-content/downloads/ScreenCapture.mp4)

**Comment by clubkert** [comment]
Hi @corbrink - thanks for reporting this and for the helpful screenshot. We've been able to debug and we have a fix that should be released this week.

**Comment by clubkert** [comment]
Hi @corbrink - the latest version of EditorsKit (1.31.3) has fixed this issue. Please let us know if this isn't solved. Thanks!
