### ISSUE TITLE
Erroneous classes added

### ISSUE THREAD

**Issue by antonyjsmith** [extendify/block-options#331]
Further to my reported issue on the Wordpress forums I've validated this in a fresh install of 5.8 with Twenty Twenty-One Theme only.

https://wordpress.org/support/topic/editors-kit-adding-incorrect-classes-to-blocks/

A simple example is overriding the font size on the paragraph block incorrectly inserts the `.has-background` class causing layout issues in the editor.

Without EditorsKit

![Screenshot 2021-08-08 at 13 37 12](https://user-images.githubusercontent.com/2427859/128632194-54661dd5-3571-4831-b1db-ec7b3caeebd7.png)

With EditorsKit

![Screenshot 2021-08-08 at 13 31 16](https://user-images.githubusercontent.com/2427859/128632156-3ab53711-16fa-40e2-8ef0-3688b8d41177.png)

**Comment by clubkert** [comment]
Hi @antonyjsmith - thanks again for reporting this and for including helpful information that helped in debugging. As I mentioned in the support thread, we've worked on a fix for this and it will go out in the next release.
